#! /bin/sh

# Start polybar
launch-polybar &

# Monitor Setup
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc monitor HDMI2 -a 1 2 3 4 5
bspc monitor VGA1 -a 6 7 8 8 9
bspc monitor LVDS1 -a 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
