#! /bin/sh
bspc rule -r "*" # remove all rules first

# Enable windwos swallowing
pidof bspswallow || bspswallow &

# Launch Polybar
launch-polybar &

# General Settings
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config automatic_scheme     alternate
bspc config intial_polarity      first_child
bspc config directional_focus_tightness high
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Monitor Setup
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

i=1
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( 10 / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))`
    i=$(( i + per ))
done

# Pointer configuration
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Colors
bspc config focused_border_color "#E84F4F"

# Window Rules
bspc rule -a Arandr state=floating rectangle=800x500+150+150 sticky=on
bspc rule -a Galculator state=floating rectangle=500x500+150+150 sticky=on
